name: Release workflow
on: push

jobs:
  check_linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 . --count --show-source --max-line-length=127 --statistics
  check_docker:
    runs-on: ubuntu-latest
    name: A job to check Docker compilation
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Docker step
        uses: ./
        id: test_docker
        env:
          CRYPTOGRAPHY_BOT_TOKEN: "None"